work_upload/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.work_upload_List.as_view()),
    #path('',views.index),
    path('<int:pk>/', views.PostUpdate.as_view(), name='review_edit'),
    #path('<int:pk>/', views.single_post_page),
    path('search/<str:q>/', views.PostSearch.as_view()),

    path('create_work_upload/', views.PostCreate.as_view()),

    path('<int:pk>/delete/', views.delete_post),

    path('loginout/', include('loginout.urls')),

]

work_upload/models.py
from django.db import models

class Post(models.Model):

    xfa_num = (('Number1', 'Number1'),('Number2', 'Number2'),('Number3', 'Number3'),('Number4', 'Number4'),('Number5', 'Number5'),('Number6', 'Number6'))
    tspi_yn = (('Y', 'Y'), ('N', 'N'))
    

    flight_name = models.CharField(max_length=30)
    flight_date = models.DateField()
    flight_num = models.CharField(max_length=10, choices=xfa_num)

    inetx_ver = models.CharField(max_length=5)
    cal_ver = models.CharField(max_length=5)

    tspi_ch = models.CharField(max_length=4, choices=tspi_yn)

    created_at = models.DateTimeField()
    writer_name = models.CharField(max_length=10)

    def __str__(self):
        return f'[{self.pk}] {self.flight_name}'

    def get_absolute_url(self):
        return f'/work_upload/{self.pk}/'

# Create your models here.


work_upload/views.py
#from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post
from django.db.models import Q

from django.shortcuts import render, get_object_or_404, redirect

class work_upload_List(LoginRequiredMixin, UserPassesTestMixin, ListView):
    
    login_url = 'loginout/login'

    model = Post
    template_name = 'work_upload/index.html'
    ordering = '-pk'
    ...
    paginate_by = 10

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff or self.request.user.is_active
    


    def get_context_data(self, **kwargs):

        context = super(work_upload_List, self).get_context_data()
        ...
        page = context['page_obj']
        paginator = page.paginator
        pagelist = paginator.get_elided_page_range(page.number, on_each_side=3, on_ends=1)
        context['pagelist'] = pagelist
        ...

        return context

# def index(request):
#     posts = Post.objects.all().order_by('-pk')

#     return render(request,'work_upload/index.html',
#     {
#         'posts_vi' : posts,
#     }
    
#     )

class PostDetail(DetailView):
    model = Post
    template_name = 'work_upload/single_post_page.html'


# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk)

#     return render( request, 'work_upload/single_post_page.html',
#     {
#         'post_vi' : post,
#     }
#     )
# Create your views here.

class PostSearch(work_upload_List):
    paginate_by = 10

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(flight_name__contains=q)).distinct()
        return post_list
    
    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'

        return context


class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    template_name = 'work_upload/create_work_upload.html'

    fields = ['flight_name','flight_date','flight_num','inetx_ver','cal_ver','tspi_ch','created_at','writer_name']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


class PostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'work_upload/single_post_page.html'
    success_url = '/work_upload/'
    

    fields = ['flight_name','flight_date','flight_num','inetx_ver','cal_ver','tspi_ch','created_at','writer_name']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

def delete_post(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('/work_upload/')

work_upload/templates/work_upload/create_work_upload.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Create Work_List - Upload</title>
        <link href="{% static 'checklist/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
       

    </head>
    <body>
        {% include "work_upload/nav.html" %}

          <div class="container-fluid">
            <div class="row">

                <div class="col-2">
                   {% include "work_upload/left_side.html" %}
                </div>

                <div class="col-10 mt-5">
                  <h4><div class="ml-2 mb-3">Create New Post</div></h4>
                    <div class="temp-box" style="overflow:auto">
                        <form method="post" enctype="multipart/form-data">{% csrf_token %}
                            
                            

                            <table class="table table-hover">
                                <tbody>
                                   
                                    <tr>
                                        <th style="width: 20%"><label for="id_flight_name" class="form-label">Flight name:</label></th>
                                        <td>                                  
                                            <input name="flight_name" maxlength="30" required="" id="id_flight_name" type="text" class="form-control col-3" placeholder="XFA1_0000_1File_230101">
                                        </td>
                                    </tr>
                                  
                                    <tr>
                                        <th><label for="id_flight_date">Flight date:</label></th>
                                        <td>                                 
                                            <input name="flight_date" required="" id="id_flight_date" type="date" class="form-control col-2">
                                        </td>
                                    </tr>
                                    
                                    <tr>
                                        <th><label for="id_flight_num">Flight num:</label></th>
                                        <td>
                                            <select name="flight_num" required="" id="id_flight_num" class="form-control col-1">
                                                <!-- <option value="" selected="">---------</option> -->                        
                                                <option value="XFA1">XFA1</option>                            
                                                <option value="XFA2">XFA2</option>                           
                                                <option value="XFA3">XFA3</option>
                                                <option value="XFA1">XFB1</option>                            
                                                <option value="XFA2">XFA4</option>                           
                                                <option value="XFA3">XFB2</option>
                                            </select>  
                                        </td>
                                    </tr>

                                    <tr>
                                        <th><label for="id_inetx_ver">Inetx ver:</label></th>
                                        <td>
                                            <input name="inetx_ver" maxlength="5" required="" id="id_inetx_ver" type="text" class="form-control col-1">
                                        </td>
                                    </tr>
                            
                                    <tr>
                                        <th><label for="id_cal_ver">Cal ver:</label></th>
                                        <td> 
                                            <input name="cal_ver" maxlength="5" required="" id="id_cal_ver" type="text" class="form-control col-1">
                                        </td>
                                    </tr>
                            
                                    <tr>
                                        <th><label for="id_tspi_ch">Tspi ch:</label></th>
                                        <td>
                                            <select name="tspi_ch" required="" id="id_tspi_ch" class="form-control col-1">
                                                                         
                                                <option value="Y">Y</option>                          
                                                <option value="N">N</option>
                                            </select>  
                                        </td>
                                    </tr>
                            
                                    <tr>
                                        <th><label for="id_created_at">Created at:</label></th>
                                        <td>                        
                                           <input name="created_at" required="" id="id_created_at" type="date" class="form-control col-2">
                                        </td>
                                    </tr>

                                     <tr>
                                        <th><label for="id_writer_name">Writer name:</label></th>
                                        <td>
                                            <input name="writer_name" maxlength="10" required="" id="id_writer_name" type="text" class="form-control col-1">
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <hr/>
                            
                            <a class="btn btn-danger" href="/work_upload/" role="button">Cancel</a>
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                            
                        </form>
                            
                    </div>
                    
              </div>

            </div>
                      
        </div>
        


          <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
          <script>document.getElementById('id_flight_date').value = new Date().toISOString().substring(0, 10);;</script>
          <script>document.getElementById('id_created_at').value = new Date().toISOString().substring(0,10);;</script>
    </body>
    <hr/>
    {% include "work_upload/footer.html" %}
    
</html>

work_upload/templates/work_upload/footer.html

    <footer style="background-color: #ddddddce;" class="container-fluid navbar-fixed-bottom">
        
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <p class="text-black py-4 m-0">&copy; Copyright 2023 - Made by Jisup.Kim</p>
                </div>
            </div>
        </div>
      
    </footer>

work_upload/templates/work_upload/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>PDPS Log Record</title>
        <link href="{% static 'checklist/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
       

    </head>
    <body>
        {% include "work_upload/nav.html" %}

          <div class="container-fluid">
            <div class="row">

                <div class="col-2">
                  {% include "work_upload/left_side.html" %}
                </div>

                <div class="col-10 mt-5">
                  <div class="row">
                      <div class="col-10">
                        <h4>
                          <div class="ml-2 mb-4">
                            Lists
                            {% if search_info %}<small class="text-muted">&nbsp;&nbsp;&nbsp;{{ search_info }}</small>{% endif %}
                          </div>
                        </h4>
                      </div>
                  
                      <div class="ml-auto mr-4">
                        {% if user.is_authenticated %}
                          {% if user.is_superuser or user.is_staff %}
                            <a href="/work_upload/create_work_upload/" class="btn btn-primary">Upload</a>
                          {% endif %}
                        {% endif %}
                        
                      </div>
                  </div>


                    <div class="temp-box" style="overflow:auto">

                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th scope="col">Flight Name</th>
                                <th scope="col">Flight Date</th>
                                <th scope="col">Day</th>
                                <th scope="col">Number</th>
                                <th scope="col">WA</th>
                                <th scope="col">TSPI</th>
                                <th scope="col">Created Date</th>
                                <th scope="col">Writer</th>
                                {% if user.is_authenticated %}
                                  {% if user.is_superuser or user.is_staff %}
                                    <th scope="col">Delete</th>
                                  {% endif %}
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for post in post_list %}
                                
                                <tr>
                                  {% if user.is_authenticated %}
                                    {% if user.is_superuser or user.is_staff %}
                                      <td><a href="{{ post.get_absolute_url }}">{{ post.flight_name }}</a></td>
                                    {% else %}
                                      <td>{{ post.flight_name }}</td>
                                    {% endif %}
                                  {% endif %}
                                    <td>{{ post.flight_date|date:"Y.m.d" }}</td>
                                    <td>{{ post.flight_date|date:"l" }}</td>
                                    <td>{{ post.flight_num }}</td>
                                    <td>{{ post.inetx_ver}}_{{post.cal_ver}}</td>
                                    <td>{{ post.tspi_ch }}</td>
                                    <td>{{ post.created_at|date:"Y.m.d" }}</td>
                                    <td>{{ post.writer_name }}</td>
                                    <input id="posts_pks" type="hidden" value="{{ post.pk }}">
                                    <!-- <td><a class="btn btn-outline-danger btn-sm" href="{{ post.get_absolute_url }}delete" role="button">Delete</a></td> -->
                                    {% if user.is_authenticated %}
                                      {% if user.is_superuser or user.is_staff %}
                                        <td><a class="btn btn-outline-danger btn-sm" onclick="fn_del_post(posts_pks.value);" role="button">Delete</a></td>
                                      {% endif %}
                                    {% endif %}
                                
                                  </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    

              </div>
            </div>
            <div class="container-fluid">
              <div class="row">

                
                <div class="mb-4 ml-auto">
                        <div class="container-fluid">
                          <div class="input-group">
                            <input class="form-control mr-1" type="text" placeholder="Search for..." id="search-input">
                            <button class="btn btn-outline-success" type="button" onclick="searchPost();">Search</button>
                          </div>
                        </div>
                </div>
              </div>
            </div>
              <div class="ml-auto">
                      <ul class="pagination justify-content-center mb-4">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr;</a>
                        </li>
                        {% else %}
                          <li class="page-item disabled">
                            <a class="page-link" href="#">&larr;</a>
                          </li>
                        {% endif %}
                        
                        {% for index in pagelist %}
                          
                          {% if index == page_obj.number %}
                          <li class="page-item active">
                            <span class="page-link">{{ index }}</span>
                          </li>
                          {% else %}
                              {% if '…' in index %}
                               <li class="page-item disabled">
                                 <a class="page-link" href="?page={{ index }}">{{ index }}</a>
                               </li>
                              {% else %}
                                <li class="page-item">
                                  <a class="page-link" href="?page={{ index }}">{{ index }}</a>
                                </li>
                                {% endif %}


                          {% endif %}
                        {% endfor %}

                          {% if page_obj.has_next %}
                        <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rarr;</a>
                        </li>
                        {% else %}
                          <li class="page-item disabled">
                            <a class="page-link" href="#">&rarr;</a>
                          </li>
                        {% endif %}
                      </ul>
              </div>
            
            
          
        </div>



          <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
          <script>
            function searchPost(){
              let searchValue = document.getElementById('search-input').value.trim();
              if (searchValue.length > 1){
                location.href="/work_upload/search/" + searchValue + "/";
              }
              else{
                alert('검색어('+ searchValue +')가 너무 짧습니다.');
              }
            };

            document.getElementById('search-input').addEventListener('keyup', function(event)
            {
              if(event.key === 'Enter'){
                searchPost();
                }
              });
          </script>
          <script>
            function fn_del_post(a){
            
              var res = confirm('게시글을 정말로 삭제하시겠습니까?');
              if(res){
                
                window.location.href = a + "/delete";
                alert("성공적으로 삭제되었습니다.");
              }
            }
          </script>
          
    </body>
    {% include "work_upload/footer.html" %}
</html>

work_upload/templates/work_upload/left_side.html
<h5><div class="ml-2 mb-3">Flight Number</div></h5>
<div class="list-group">
    <a href="/work_upload/" class="list-group-item list-group-item-action" aria-current="true">
      ALL
    </a>
    <a href="/work_upload/search/Number1/" class="list-group-item list-group-item-action">Flight_Number_1</a>
    <a href="/work_upload/search/Number2/" class="list-group-item list-group-item-action">Flight_Number_2</a>
    <a href="/work_upload/search/Number3/" class="list-group-item list-group-item-action">Flight_Number_3</a>
    <a href="/work_upload/search/Number4/" class="list-group-item list-group-item-action">Flight_Number_4</a>
    <a href="/work_upload/search/Number5/" class="list-group-item list-group-item-action">Flight_Number_5</a>
    <a href="/work_upload/search/Number6/" class="list-group-item list-group-item-action">Flight_Number_6</a>
    
  </div>

  <div class="card mb-4 my-4">
    <div class="card-header">Check List<a class="float-right" data-toggle="modal" data-target="#staticBackdrop">+ more</a></ul> </div>
    <div class="modal fade" id="staticBackdrop" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">구현 예정</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              해당 기능은 아직 사용할 수 없습니다.
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              
            </div>
          </div>
        </div>
      </div>
    <div class="card-body">
        <div class="row">
            <div class="">
                <ul class="list-unstyled mb-0 ml-3">
                    <li><a href="#!">Unique ID</a></li>
                    <li><a href="#!">Total Byte</a></li>
                    <li><a href="#!">Occurrnces</a></li>
                    <li><a href="#!">Offset Bytes</a></li>
                    <li><a href="#!">Position</a></li>
                    <li><a href="#!">Actual Rate</a></li>
                </ul>
            </div>
        </div>
    </div>
 </div>

work_upload/templates/work_upload/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mt-2 mb-5">
    <div class="container-fluid">
    <a class="navbar-brand">Flight</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#">Home</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="/work_upload/">Data Process List<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Work History</a>
        </li>
        <li class="nav-item">
          <!-- <a class="nav-link" href="/checklist/lists/">Check List</a> -->
          <a class="nav-link" href="#">Check List</a>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Working Area
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>   
      </ul>
      <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'loginout:logout' %}">Log Out</a>
              {% else %}
                <a class="nav-link" href="{% url 'loginout:login' %}">Log In</a>
              {% endif %}
          </li>
      </ul>
    </div>
    </div>
  </nav>

work_upload/templates/work_upload/single_post_page.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html>
    <head>
        <title>{{ post.flight_name }}</title>
        <link href="{% static 'checklist/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
       

    </head>
    <body>
        {% include "work_upload/nav.html" %}

          <div class="container-fluid">
            <div class="row">

                <div class="col-2">
                    {% include "work_upload/left_side.html" %}
                </div>

                <div class="col-10">
                    <h4><div class="mb-3 mt-5">Edit Post</div></h4>
                    <hr/>
                      <div class="temp-box">
                          <form method="post" enctype="multipart/form-data">{% csrf_token %}
                            
                            <div class="row">
                                <div class="col-3">
                                    {{ form.flight_name|as_crispy_field }}
                                </div>
                                <div class="col-3">
                                    {{ form.flight_date|as_crispy_field }}
                                </div>
                                <div class="col-2">
                                    {{ form.flight_num|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-2">
                                    {{ form.inetx_ver|as_crispy_field }}
                                </div>
                                <div class="col-2">
                                    {{ form.cal_ver|as_crispy_field }}
                                </div>
                                <div class="col-2">
                                    {{ form.tspi_ch|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-3">
                                    {{ form.created_at|as_crispy_field }}
                                </div>
                                <div class="col-2">
                                    {{ form.writer_name|as_crispy_field }}
                                </div>
                            </div>
                            
                            <hr/>
                            <button type="submit" class="btn btn-primary float-right ml-2">Save</button>
                            <button role="button" href = "/work_upload/" class="btn btn-secondary">Cancel</button>
                            
                            
                          </form>
                      </div>
  
                </div>
            </div>
            
            
          
        </div>



          <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    </body>
    {% include "work_upload/footer.html" %}
</html>
