loginout/urls.py
from re import template
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'loginout'

urlpatterns = [
    
    path('login/', auth_views.LoginView.as_view(template_name='loginout/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

loginout/views.py
from django.shortcuts import render

# Create your views here.

loginout/templates/loginout/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
<div>
    <strong>{{ field.label }}</strong>
    {{ field.errors }}
</div>
{% endif %}
{% endfor %}
<!-- 넌필드 오류 -->
{% for error in form.non_field_errors %}
<div>
    <strong>{{ error }}</strong>
</div>
{% endfor %}
</div>
{% endif %}

loginout/templates/loginout/login.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <title>Log in</title>
        <link href="{% static 'checklist/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
       

    </head>
    <body class="text-center">
        <div class="container-fluid my-3">
            <div class="row">
            <div class="col-4">

            </div>
            <div class="col-4">
            <h1>&nbsp</h1>
            <hr/>
            <h2>Please sign in</h2>
            <hr/>
            <form method="post" action="{% url 'loginout:login' %}">
                {% csrf_token %}
                {% include "loginout/form_errors.html" %}
                <div class="mb-3">
                    <label for="username">User ID</label>
                    <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
                </div>
                
                <button type="submit" class="btn btn-primary">Sign in</button>
                <p class="mt-5 mb-3 text-muted">© 2022–2023</p>
            </form>
            </div>
            </div>
        </div>
    </body>

</html>